title: shpik's world
author: shpik
email: shpik.korea@gmail.com
description: >
  Security engineer interested in Web, Pwnable and Browsers(Chrome).

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- about.md
- posts.md

footer_icons:
- username: shpik
  url: https://github.com/shpik-kr/
  icon: icon-github.svg

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec

theme: aterenin/minima-reboot